#pragma once 

#include "CommonHeaders.h"

namespace NN
{

	
//
//Activation Function 
//

const std::string activationFunctionsSrc = ""
"__kernel void ActivationIdentity(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x;"
"}"
"__kernel void DeltaActivationIdentity(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = 1;"
"}"
""
"__kernel void ActivationBinaryStep(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? 0 : 1;"
"}"
"__kernel void DeltaActivationBinaryStep(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = 0;"
"}"
""
"__kernel void ActivationLogistic(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = 1.0 /(1.0 + exp(-x));"
"}"
"__kernel void DeltaActivationLogistic(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	float f = 1.0 /(1.0 + exp(-x));"
"	y[base] = f * (1.0 - f);"
"}"
""
"__kernel void ActivationTanH(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = tanh(x);"
"}"
"__kernel void DeltaActivationTanH(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	float f = tanh(x);"
"	y[base] = 1.0 - f * f;"
"}"
""
"__kernel void ActivationArcTan(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = atan(x);"
"}"
"__kernel void DeltaActivationArcTan(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = 1.0/(x * x + 1);"
"}"
""
"__kernel void ActivationSoftSign(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x / (1.0 + fabs(x));"
"}"
"__kernel void DeltaActivationSoftSign(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	float f = 1.0 + fabs(x);"
"	y[base] = 1.0 / (f * f);"
"}"
""
"__kernel void ActivationReLU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? 0 : x;"
"}"
"__kernel void DeltaActivationReLU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? 0 : 1;"
"}"
""
"__kernel void ActivationLeakyReLU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? 0.01 * x : x;"
"}"
"__kernel void DeltaActivationLeakyReLU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? 0.01 : 1;"
"}"
""
"__kernel void ActivationLeakyPReLU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? param0 * x : x;"
"}"
"__kernel void DeltaActivationLeakyPReLU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? param0 : 1;"
"}"
""
"__kernel void ActivationELU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = x < 0 ? param0 * (exp(x) - 1.0) : x;"
"}"
"__kernel void DeltaActivationELU(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	float f = param0 * (exp(x) - 1.0);"
"	y[base] = x < 0 ? f + param0 : 1;"
"}"
""
"__kernel void ActivationSoftPlus(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = log(1.0 + exp(x));"
"}"
"__kernel void DeltaActivationSoftPlus(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = 1.0 / (1.0 + exp(-x));"
"}"
""
"__kernel void ActivationGaussian(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = exp(-x * x);"
"}"
"__kernel void DeltaActivationGaussian(__global float* v, __global float* y, float param0, float param1)"
"{"
"	int base = get_global_id(0);"
"	float x = v[base];"
"	y[base] = -2 * x * exp(-x * x);"
"}"
;

}